name: Daily News Brief

on:
  schedule:
    # Runs at 23:00 UTC = 06:00 WIB (Next Day)
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # PENTING: Supaya boleh save file
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Run PowerShell Script
      shell: pwsh
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOKEN_2: ${{ secrets.TELEGRAM_TOKEN_2 }}
        TELEGRAM_CHAT_ID_2: ${{ secrets.TELEGRAM_CHAT_ID_2 }}
      run: |
        ./fetch_news_cloud.ps1

    - name: Commit and Push News JSON
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add news.json
        git commit -m "Update news.json" || exit 0
        git push
